export default function createInvoiceEntity({
	id = "",
	invoiceNumber = "",
	seller = null,
	customer = null,
	invoiceDate = null,
	dueDate = null,
	currency = "",
	items = [],
	note = "",
	netTotal = 0,
	taxAmount = 0,
	grossTotal = 0,
	paidAmount = 0,
	openAmount = 0,
	paymentStatus = "",
	status = "",
	payments = [],
	createdAt = null,
	updatedAt = null,
} = {}){
	return {
		id,
		invoiceNumber,
		seller,
		customer,
		invoiceDate,
		dueDate,
		currency,
		items,
		note,
		netTotal,
		taxAmount,
		grossTotal,
		paidAmount,
		openAmount,
		paymentStatus,
		status,
		payments,
		createdAt,
		updatedAt,
	};
}
